apiVersion: v1
kind: Service
metadata:
  labels:
    app: galaxy
  name: galaxy-external
spec:
  ports:
  - name: "9898"
    port: 9898
    targetPort: 9898
  selector:
    app: irida-galaxy
  type: LoadBalancer
