apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: irida-db
  name: irida-db
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: irida-db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: test
        - name: MYSQL_ROOT_PASSWORD
          value: test
        image: 511019881784.dkr.ecr.us-west-2.amazonaws.com/dfornika/irida-db
        name: irida-db
        
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
status: {}
