apiVersion: v1
kind: Pod
metadata:
  labels:
    app: irida-galaxy
  name: irida-pod
spec:
  volumes:
    - name: global-share
      emptyDir: {}
  containers:
  - name: irida
    image: 511019881784.dkr.ecr.us-west-2.amazonaws.com/dfornika/irida:0.3
    args:
    - catalina.sh
    - run
    env:
    - name: GET_HOSTS_FROM
      value: dns
    volumeMounts:
    - mountPath: "/opt/irida/data"
      name: global-share
    ports:
    - containerPort: 8080
  - name: galaxy
    image: 511019881784.dkr.ecr.us-west-2.amazonaws.com/bccdc/irida-galaxy:0.2
    ports:
    - containerPort: 9898    
    volumeMounts:
    - mountPath: "/export"
      name: global-share
    - mountPath: "/opt/irida/data"
      name: global-share
  tolerations:
    - operator: "Exists"




    
        
        
        
        
